# Generated by Django 5.1.1 on 2024-10-18 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
