# Generated by Django 5.1.1 on 2024-10-18 13:31

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_field_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(max_length=50, validators=[students.models.field_study_validator]),
        ),
    ]
