services:
  - type: web
    name: student-management-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_project.wsgi:application"
    plan: free
    environmentVariables:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: student-management-system.onrender.com
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false  # Set your Supabase database password here
      - key: DB_HOST
        value: db.qdxuzbtqnvhjpcfdykse.supabase.co
      - key: DB_PORT
        value: 5432
