services:
  - type: web
    name: student-management-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn --bind 0.0.0.0:$PORT django_project.wsgi:application"
    plan: free
    environmentVariables:
      - key: SECRET_KEY
        generateValue: true
